---
title: "Final Project"
author: "Ziwen Lu, Xuyan Xiu, Doris Yan"
format: html
editor: visual
execute: 
  warning: false
embed-resources: true
---

```{r load libraries, echo=FALSE}
library(haven)
library(here)
library(tidyverse)
library(icpsrdata)
library(tidycensus)
library(rvest)
library(httr)
dir.create("data")
```

# Reproducible data retrieval
```{r}
options("icpsr_email" = "dy212@georgetown.edu", "icpsr_password" = "Fbp9nbmKreLsubd8nL5H")
```


## crime
```{r}
# takes 1-2 mins
icpsr_download(
  file_id = 38649,
  download_dir = here("data")
)

crime<-read_dta(here("data","ICPSR_38649","DS0001","38649-0001-Data.dta"))
```

## ses
```{r}
# takes 9-10 mins
icpsr_download(
  file_id = 38528,
  download_dir = here("data")
)

ses08_17<-read_dta(here("data","ICPSR_38528","DS0002","38528-0002-Data.dta"))
```

## school counts
```{r}
# takes 1-2 mins
icpsr_download(
  file_id = 38569,
  download_dir = here("data")
)

schoolct<-read_dta(here("data","ICPSR_38569","DS0001","38569-0001-Data.dta"))
```


## the number of parks
```{r}
# takes 1-2 mins
icpsr_download(
  file_id = 38586,
  download_dir = here("data")
)

parks<-read_dta(here("data","ICPSR_38586","DS0001","38586-0001-Data.dta"))
```

## street connectivity
```{r}
# takes 1-2 mins
icpsr_download(
  file_id = 38580,
  download_dir = here("data")
)

streetcon<-read_dta(here("data","ICPSR_38580","DS0001","38580-0001-Data.dta"))
```

## traffic
```{r}
# takes 1-2 mins
icpsr_download(
  file_id = 38584,
  download_dir = here("data")
)

traffic<-read_dta(here("data","ICPSR_38584","DS0001","38584-0001-Data.dta"))
```

## pollution
```{r}
# takes 1 min
icpsr_download(
  file_id = 38597,
  download_dir = here("data")
)

pollution<-read_dta(here("data","ICPSR_38597","DS0001","38597-0001-Data.dta"))
```

## urbanicity
```{r}
# takes 1 min
icpsr_download(
  file_id = 38606,
  download_dir = here("data")
)

urban<-read_dta(here("data","ICPSR_38606","DS0001","38606-0001-Data.dta"))
```

## land cover
```{r}
# takes 1-2 min
icpsr_download(
  file_id = 38598,
  download_dir = here("data")
)

landcover<-read_dta(here("data","ICPSR_38598","DS0001","38598-0001-Data.dta"))
```
## road system
```{r}
# takes 1-2 min
icpsr_download(
  file_id = 38585,
  download_dir = here("data")
)

road<-read_dta(here("data","ICPSR_38585","DS0001","38585-0001-Data.dta"))
```
# Clean data

## crime
```{r}
# crime data at 2013
crime_data<-crime|>
  rename_all(tolower)|>
  rename(county=stcofips)|>
  mutate(viol = murder+rape+robbery+agasslt)|>
  mutate(property = burglry+larceny+mvtheft)|>
  select(county,year,viol,property)

attr(crime_data$viol, "label")<-"Total violent crimes reported (MURDER + RAPE + ROBBERY + AGASSLT)"

attr(crime_data$property, "label")<-"Total property crimes reported (BURGLRY + LARCENY + MVTHEFT)"

crime_2013<-crime_data|>
  filter(year == 2013)
```

```{r}
clean_data<-
  function(data) {
    cleaned_data <- data |> 
      rename_all(tolower)|>
      mutate(county = substr((tract_fips10), 1, 5))|>
      select(-tract_fips10)

  return(cleaned_data)
}
```

## ses
```{r}
#  ACS five-year estimate 2013-2017
ses_2013<-clean_data(ses11_14)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)|>
  pivot_longer(
  cols = !county, 
  names_to = "indicator",
  values_to = "value"
  )|>
  filter(str_sub(indicator, -2) == "17")|>
  # pivot SES indicators back as variables
  pivot_wider(
    names_from = indicator,
    values_from = value
  )
```

## school counts
```{r}
# school counts at 2013
schoolct_2013<-clean_data(schoolct)|>
  group_by(county,year)|>
  summarise_all(sum, na.rm = TRUE)|>
  filter(year == 2013)
```

##  parks
```{r}
# from 2010 decennial census
parks_2013<-clean_data(parks)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)
```

## street connectivity
```{r}
# from 2010 decennial census
streetcon_2013<-clean_data(streetcon)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)
```

## traffic
```{r}
# traffic in 2013
traffic_2013<-clean_data(traffic)|>
  group_by(county,year)|>
  summarise_all(sum, na.rm = TRUE)|>
  filter(year == 2013)
```

## pollution
```{r}
# pollution in 2013
pollution_2013<-clean_data(pollution)|>
  group_by(county,year)|>
  summarise_all(sum, na.rm = TRUE)|>
  filter(year == 2013)
```

## urbanicity
```{r}
# from 2010 decennial census
urban_2013<-clean_data(urban)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)
```

## land cover
```{r}
# from 2010 decennial census
landcover_2013<-landcover|>
  rename_all(tolower)|>
  mutate(county = substr((tract_fips), 1, 5))|>
  select(-tract_fips)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)
```

## road system
```{r}
# from 2010 decennial census
road_2013<-clean_data(road)|>
  group_by(county)|>
  summarise_all(sum, na.rm = TRUE)
```

# Combine All Datasets

```{r}
# combine the data sets with the by "county" and "year" columns
crime_all <- full_join(
  crime_2013,
  full_join(
    ses_2013,
   full_join(
     schoolct_2013,
    full_join(
      parks_2013,
      full_join(
        streetcon_2013,
        full_join(
          traffic_2013,
          full_join(
            pollution_2013, 
            full_join(
              urban_2013,
              full_join(
                landcover_2013, road_2013, by = "county")
              ),
            by = "county"
            ),
          by = "county"
          ),
        by = "county"
        ),
      by = "county"
      ),
    by = "county"
    ),
   by = "county"
  ),
  by = "county"
)

crime_all<-crime_all|>
  select(-year.y, -year.x, -year.y.y)|>
  rename(year = year.x.x)
```

```{r}
glimpse(crime_all)
```